// src/app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/menu/navbar';
import Footer from '@/components/footer';
import Container from '@/components/container';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'Create Next App 545',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} overflow-x-hidden overflow-y-hidden sm:overflow-y-visible`}
        suppressHydrationWarning={true}
      >
        <Container>
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </Container>
      </body>
    </html>
  );
}
