import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    absolute: 'blog add',
  },
  description: 'Generated by create next app',
};
const AddBlog: React.FC = () => {
  return <div>add blog page</div>;
};

export default AddBlog;
